### ISSUE TITLE
部分命令提供坐标信息

### ISSUE THREAD

**Issue by Arcadi4** [LazyAlienServer/MainStorageSearcher#1]
建议在`!!ms list`中提供全物品样式的坐标

<img width="302" alt="image" src="https://github.com/user-attachments/assets/197f113f-9eb0-4432-a8a7-73e63ca43986">

在高亮最佳匹配和选择其它匹配时，提供目标坐标

<img width="613" alt="image" src="https://github.com/user-attachments/assets/be72a2f5-2d62-4ab3-ba7e-a62d2ebff7c1">

**Comment by tanhHeng** [comment]
将在下一版本加入
